sudo: false

language: node_js

node_js:
  - "stable"

before_install:
  - npm i -g npm@6.14.11

install:
  - npm ci

script:
  - npm run build

notifications:
  email: false

branches:
  only:
    - master
