import React from "react"

import KeyFacts from '../../../../components/RenderContentObject/KeyFacts'

import meta from './_meta.yaml'

class IndexRoute extends React.Component {
  render () {

    return (
      <section className='doc-content'>
        <h2>Historical Documents Overview</h2>

        <p>
          The vast majority of Press Releases generated by the FDA, its predecessors, and FDA-focused releases
          issued by its Departments are reproduced here for every year from 1913, the first year they became
          available, through 2014. These represent thousands of news releases capturing the diverse
          responsibilities and activities of the agency that affected every citizen over more than a century.
          While these do not necessarily drill down into the deep details of the crisis, enforcement action,
          major appointment or organizational change, public health alert, etc., there are few if any other
          sources that so extensively capture what FDA has been involved in over this period, such as
          botulism-tainted ripe olives (1920), the formation and initial meeting of the Advisory Committee
          on Abuse of Depressant and Stimulant Drugs to discuss LSD and other drugs (1965), and the
          announcement of guidance to support the responsible development of nanotechnology products (2014).
        </p>

        <p>
          As official statements from the agency, the Press Releases are carefully crafted and accurate
          representations of issues at specific points in time. They are indeed the references of record that
          the print and broadcast media depended on. As such, the FDA History Office believes the public
          generally, as well as researchers, regulated industry, the press, students, and other stakeholders
          would be interested in having access to this information. The Press Releases gathered here were
          drawn from a variety of sources, including the National Archives, the FDA library, and the
          collections of the History Office.
        </p>

        <p>
          Through the use of optical character recognition (OCR), the Press Releases have been turned into a searchable
          openFDA API endpoint.
        </p>
        <KeyFacts
          noun_name={meta.api_path.split("/")[1]}
          endpoint_name={meta.api_path.split("/")[2]}
          harmonized={false}
          status={meta.status}
        />
      </section>
    )
  }
}

export default IndexRoute



